version: '3'
services:

  broker-service:
    build:
      dockerfile: ./broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1