apiVersion: apps/v1
kind: Deployment
metadata:
  name: listerner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listerner-service
  template:
    metadata:
      labels:
        app: listerner-service
    spec:
      containers:
        - name: listerner-service
          image: "franckduche2/listener-service:1.0.0"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_DATABASE
              value: "logs"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: listerner-service
spec:
  selector:
    app: listerner-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80
